version: '3.6'
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    networks: 
      - postgresqlnetwork
      - default
    restart: always
networks:
  postgresqlnetwork:
    driver: ipvlan
    internal: true
    name: pgadminnetwork
  default: